### PR TITLE
Add Python 3

### PR DESCRIPTION
**Pull request by kynan**

### CODE REVIEW

**Comment by sodre** [comment]
I tried adding python 3 support during the initial PR. There were missing dependencies...

If you enable to python 3, you also need to rerender the recipe with conda-smithy.

**Comment by sodre** [comment]
@kynan 
re-trigger the build after conda-forge/wmctrl-feedstock#1 has been merged.

**Comment by kynan** [comment]
@sodre the pr is merged, but I don't have permission to rerun the builds

**Comment by sodre** [comment]
'git commit --amend'
'git push --force'

It will trigger the build.

**Comment by kynan** [comment]
Yes, I know I can force a rebuild that way. I'll do that then. I thought you were going to trigger a rebuild with the CI providers directly.

**Comment by sodre** [comment]
I don't think I can either. 

Patrick

**Comment by kynan** [comment]
This looks good to go now @sodre

**Pull request merged**
