### PR TITLE
Bump build number to force CI

### PR DESCRIPTION
**Pull request by kynan**

### CODE REVIEW

**Comment by kynan** [comment]
Well, that didn't work. @conda-forge/core any ideas what's happening here?

**Comment by scopatz** [comment]
@conda-forge-admin please rerender

**Comment by scopatz** [comment]
@conda-forge-admin, please update circle

**Comment by kynan** [comment]
Thanks, now we have Circle back. How do we also get Travis and Azure Pipelines? And how did we "lose" them in the first place?

**Comment by kmuehlbauer** [comment]
@kynan AFAIK, noarch just builds on Circle.

**Comment by scopatz** [comment]
Yeah, noarch python are just on circle

**Comment by kynan** [comment]
Oh, of course, my bad! I think we're good then, thanks!

**Comment by megies** [comment]
Thanks @scopatz @mariusvniekerk for helpin out!

**Pull request merged**
