### PR TITLE
do proper testing if the package really works

### PR DESCRIPTION
**Pull request by megies**
also increment build number

ref: conda-forge/staged-recipes#3215

### CODE REVIEW

**Comment by sodre** [comment]
@megies,

Would you like to be included as an additional maintainer?

**Comment by megies** [comment]
> @megies,
> 
> Would you like to be included as an additional maintainer?

Your call, I mainly just wanted to be able to install this via conda. But I can also try to help keep it up to date if you like.

**Comment by sodre** [comment]
an additional maintainer would be awesome. I am adding you as part of the merge.

**Comment by megies** [comment]
OK, fine, thanks!

**Pull request merged**
